"""
Autonomous Goal Generation — the unified consciousness sets its own goals.

A pro player doesn't follow a config file. They:
- Observe the server state and identify opportunities
- Generate goals based on expected value
- Prioritize goals by expected return
- Decompose goals into actionable tasks
- Self-measure and adjust

This module wires into:
- unified_consciousness.py: sets goals based on world model
- goal_decomposer.py: decomposes goals into tasks
- PDCA loop: executes the goal plan
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from threading import RLock
from typing import Any

logger = logging.getLogger(__name__)


class GoalCategory(Enum):
    """Categories of autonomous goals."""
    LEVELING = "leveling"
    ECONOMY = "economy"
    GEAR_UPGRADE = "gear_upgrade"
    JOB_ADVANCEMENT = "job_advancement"
    TERRITORY_EXPANSION = "territory_expansion"
    ALLIANCE_BUILDING = "alliance_building"
    WOE_PREPARATION = "woe_preparation"
    CRAFTING = "crafting"
    QUESTING = "questing"
    EXPLORATION = "exploration"
    SURVIVAL = "survival"
    MARKET_DOMINATION = "market_domination"
    MVP_HUNTING = "mvp_hunting"
    SKILL_MASTERY = "skill_mastery"


@dataclass
class AutonomousGoal:
    """A goal generated by the autonomous system."""
    category: GoalCategory
    description: str
    expected_value: float  # Expected return on investment
    priority: int  # 1-10
    prerequisites: list[str] = field(default_factory=list)
    estimated_duration: float = 0.0  # seconds
    status: str = "pending"  # pending, active, completed, failed
    created_at: float = 0.0
    completed_at: float = 0.0
    result: str = ""
    metrics: dict[str, Any] = field(default_factory=dict)


@dataclass
class Opportunity:
    """An observed opportunity in the game world."""
    description: str
    category: GoalCategory
    expected_value: float
    confidence: float  # 0.0-1.0
    evidence: str = ""
    expires_at: float = 0.0
    map_name: str = ""
    required_level: int = 0
    required_zeny: int = 0


class AutonomousGoalGenerator:
    """Generates autonomous goals based on server state observations.

    The unified consciousness uses this to:
    1. Observe the server state (economy, competition, events)
    2. Identify opportunities (high-value maps, market gaps, events)
    3. Generate goals with expected value estimates
    4. Prioritize goals by expected return
    5. Track goal progress and adjust
    """

    def __init__(self):
        self._lock = RLock()
        self._active_goals: list[AutonomousGoal] = []
        self._completed_goals: list[AutonomousGoal] = []
        self._opportunities: list[Opportunity] = []
        self._stats: dict[str, int] = {
            "goals_generated": 0,
            "goals_completed": 0,
            "goals_failed": 0,
            "opportunities_identified": 0,
        }

    # ── Opportunity Detection ──

    def detect_opportunities(self, signals: dict[str, Any]) -> list[Opportunity]:
        """Detect opportunities from server state signals."""
        opportunities = []
        now = time.time()

        # Leveling opportunity: check if current map has good EXP
        base_level = int(signals.get("base_level", 1) or 1)
        job_level = int(signals.get("job_level", 0) or 0)
        zeny = int(signals.get("zeny", 0) or 0)
        map_name = str(signals.get("map", ""))
        kpm = float(signals.get("kills_per_min", 0) or 0)
        exp_rate = float(signals.get("base_exp", 0) or 0)

        # Good leveling spot
        if kpm > 10 and exp_rate > 0:
            opportunities.append(Opportunity(
                description=f"Good leveling spot on {map_name} ({kpm:.0f} KPM)",
                category=GoalCategory.LEVELING,
                expected_value=min(10.0, kpm / 10),
                confidence=0.7,
                evidence=f"KPM={kpm:.1f}, EXP rate={exp_rate}",
                expires_at=now + 3600,
                map_name=map_name,
            ))

        # Job advancement opportunity
        if base_level >= 40 and job_level >= 40:
            opportunities.append(Opportunity(
                description="Ready for job advancement",
                category=GoalCategory.JOB_ADVANCEMENT,
                expected_value=15.0,
                confidence=0.8,
                evidence=f"Base={base_level}, Job={job_level}",
                expires_at=now + 86400,
            ))

        # Gear upgrade opportunity
        if zeny > 50000:
            opportunities.append(Opportunity(
                description=f"Can afford gear upgrades ({zeny:,}z available)",
                category=GoalCategory.GEAR_UPGRADE,
                expected_value=8.0,
                confidence=0.6,
                evidence=f"Zeny={zeny}",
                required_zeny=50000,
                expires_at=now + 7200,
            ))

        # Market opportunity
        if zeny > 100000:
            opportunities.append(Opportunity(
                description=f"Market trading opportunity ({zeny:,}z capital)",
                category=GoalCategory.ECONOMY,
                expected_value=12.0,
                confidence=0.5,
                evidence=f"Capital={zeny}",
                required_zeny=100000,
                expires_at=now + 3600,
            ))

        # Exploration opportunity
        if base_level > 20 and not map_name:
            opportunities.append(Opportunity(
                description="Explore new maps for better farming",
                category=GoalCategory.EXPLORATION,
                expected_value=5.0,
                confidence=0.4,
                evidence="Current map unknown or suboptimal",
                expires_at=now + 1800,
            ))

        with self._lock:
            self._opportunities.extend(opportunities)
            self._stats["opportunities_identified"] += len(opportunities)
            # Keep last 50 opportunities
            if len(self._opportunities) > 50:
                self._opportunities = self._opportunities[-50:]

        return opportunities

    # ── Goal Generation ──

    def generate_goals(self, signals: dict[str, Any]) -> list[AutonomousGoal]:
        """Generate autonomous goals from detected opportunities and state."""
        goals = []
        now = time.time()

        # Detect opportunities first
        opportunities = self.detect_opportunities(signals)

        # Convert high-value opportunities to goals
        for opp in opportunities:
            if opp.expires_at > now and opp.expected_value > 3.0:
                goal = AutonomousGoal(
                    category=opp.category,
                    description=opp.description,
                    expected_value=opp.expected_value,
                    priority=self._calculate_priority(opp, signals),
                    estimated_duration=self._estimate_duration(opp.category),
                    created_at=now,
                    metrics={
                        "confidence": opp.confidence,
                        "evidence": opp.evidence,
                        "map": opp.map_name,
                    },
                )
                goals.append(goal)

        # Add survival goal if HP/SP is low
        hp_ratio = float(signals.get("hp_ratio", 1.0) or 1.0)
        sp_ratio = float(signals.get("sp_ratio", 1.0) or 1.0)
        if hp_ratio < 0.3 or sp_ratio < 0.2:
            goals.append(AutonomousGoal(
                category=GoalCategory.SURVIVAL,
                description=f"Recover HP ({hp_ratio:.0%}) and SP ({sp_ratio:.0%})",
                expected_value=20.0,
                priority=10,
                estimated_duration=30.0,
                created_at=now,
            ))

        # Add leveling goal if no other high-value goals
        if not any(g.expected_value > 5.0 for g in goals):
            goals.append(AutonomousGoal(
                category=GoalCategory.LEVELING,
                description=f"Level up on optimal map (current: {signals.get('map', 'unknown')})",
                expected_value=5.0,
                priority=5,
                estimated_duration=1800.0,
                created_at=now,
            ))

        with self._lock:
            # Sort by priority and keep top 5
            goals.sort(key=lambda g: -g.priority)
            self._active_goals = goals[:5]
            self._stats["goals_generated"] += len(goals)

        return self._active_goals

    def _calculate_priority(self, opp: Opportunity, signals: dict) -> int:
        """Calculate priority based on opportunity value and current state."""
        base_priority = int(opp.expected_value)

        # Boost survival-related goals
        if opp.category == GoalCategory.SURVIVAL:
            return 10

        # Boost based on confidence
        if opp.confidence > 0.8:
            base_priority += 2
        elif opp.confidence > 0.6:
            base_priority += 1

        # Boost if we have the resources
        zeny = int(signals.get("zeny", 0) or 0)
        if opp.required_zeny > 0 and zeny >= opp.required_zeny:
            base_priority += 1

        # Cap at 10
        return min(10, max(1, base_priority))

    def _estimate_duration(self, category: GoalCategory) -> float:
        """Estimate how long a goal will take."""
        estimates = {
            GoalCategory.LEVELING: 1800.0,
            GoalCategory.ECONOMY: 600.0,
            GoalCategory.GEAR_UPGRADE: 300.0,
            GoalCategory.JOB_ADVANCEMENT: 1200.0,
            GoalCategory.TERRITORY_EXPANSION: 3600.0,
            GoalCategory.ALLIANCE_BUILDING: 1800.0,
            GoalCategory.WOE_PREPARATION: 7200.0,
            GoalCategory.CRAFTING: 600.0,
            GoalCategory.QUESTING: 900.0,
            GoalCategory.EXPLORATION: 300.0,
            GoalCategory.SURVIVAL: 30.0,
            GoalCategory.MARKET_DOMINATION: 3600.0,
            GoalCategory.MVP_HUNTING: 1800.0,
            GoalCategory.SKILL_MASTERY: 600.0,
        }
        return estimates.get(category, 600.0)

    # ── Goal Tracking ──

    def get_top_goal(self) -> AutonomousGoal | None:
        """Get the highest priority active goal."""
        with self._lock:
            active = [g for g in self._active_goals if g.status == "pending" or g.status == "active"]
            if not active:
                return None
            return max(active, key=lambda g: g.priority)

    def mark_goal_completed(self, goal_description: str, result: str = "") -> None:
        """Mark a goal as completed."""
        with self._lock:
            for goal in self._active_goals:
                if goal.description == goal_description and goal.status != "completed":
                    goal.status = "completed"
                    goal.completed_at = time.time()
                    goal.result = result
                    self._completed_goals.append(goal)
                    self._stats["goals_completed"] += 1
                    logger.info("autonomous_goal_completed: %s", goal_description)
                    break

    def mark_goal_failed(self, goal_description: str, reason: str = "") -> None:
        """Mark a goal as failed."""
        with self._lock:
            for goal in self._active_goals:
                if goal.description == goal_description and goal.status != "failed":
                    goal.status = "failed"
                    goal.result = reason
                    self._stats["goals_failed"] += 1
                    logger.info("autonomous_goal_failed: %s - %s", goal_description, reason)
                    break

    def get_goal_context(self) -> str:
        """Get formatted goal context for LLM prompts."""
        with self._lock:
            lines = ["── Autonomous Goals ──"]
            active = [g for g in self._active_goals if g.status in ("pending", "active")]
            if active:
                for g in active[:5]:
                    lines.append(
                        f"  [P{g.priority}] {g.description} "
                        f"(value={g.expected_value:.1f}, est={g.estimated_duration:.0f}s)"
                    )
            completed = self._completed_goals[-3:]
            if completed:
                lines.append("  Recent completions:")
                for g in completed:
                    lines.append(f"    ✓ {g.description}")
            lines.append(f"  Stats: {self._stats['goals_generated']} generated, "
                        f"{self._stats['goals_completed']} completed, "
                        f"{self._stats['goals_failed']} failed")
            return "\n".join(lines)

    def counters(self) -> dict[str, int]:
        with self._lock:
            return dict(self._stats)


# ── Global Singleton ──

_goal_generator: AutonomousGoalGenerator | None = None
_goal_generator_lock = RLock()


def get_goal_generator() -> AutonomousGoalGenerator:
    global _goal_generator
    with _goal_generator_lock:
        if _goal_generator is None:
            _goal_generator = AutonomousGoalGenerator()
        return _goal_generator
