"""
Macro Agent — AI generates + verifies OpenKore macros for specific cases.

The agent is SELF-IMPROVING: it generates a macro for a case, verifies it
(parse + security + dry-run + outcome), and on live outcome it is REWARDED or
PUNISHED via the BrainRewardLedger. A macro that repeatedly wins is promoted to
the shared registry (committed, reusable by other users); one that fails is
demoted/removed. This is the "macro-agent as self-learning/self-healing/
self-improving skill-set" the user asked for.

Flow:
  1. generate(case, context)  -> LLM proposes a macro (via ModelRouter.generate_text)
  2. verify(macro)            -> MacroVerifier (parse+security+dryrun+outcome)
  3. register(macro)          -> add to MacroIntelligence as a MacroPattern (skill-set)
  4. publish(macro)            -> MacroCompiler + MacroPublisher -> control/*.txt
  5. reward/punish on outcome  -> BrainRewardLedger.record(bot, "macro", event)
  6. promote/demote           -> shared registry (macros/ dir + manifest)

Agnostic (RULE.md): the agent NEVER hardcodes item/map/server names. Server
facts (guild map, NPC coords, item names) come from the server_solutions store /
job_change_locations table via the caller-provided context. The LLM prompt
instructs it to use @keyword() placeholders and DB-backed slots only.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

from ai_sidecar.autonomy.macro_verifier import MacroVerifier, MacroVerification

logger = logging.getLogger(__name__)

# ── Reward/punish events for the macro brain (BrainRewardLedger) ─────────
MACRO_REWARD = "objective"          # macro achieved its goal (job change, kill, etc.)
MACRO_PUNISH = "repeated_failure"   # macro failed / caused a death / stuck loop

# ── Registry manifest ─────────────────────────────────────────────────────
_REGISTRY_NAME_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")


@dataclass(slots=True)
class GeneratedMacro:
    """A macro generated by the agent, with verification + reward state."""
    name: str
    lines: list[str]
    case: str = ""                  # the specific case this macro handles
    category: str = "custom"        # skill-set category (job_change, vitals, ...)
    priority: int = 50
    triggers: list[dict[str, Any]] = field(default_factory=list)
    exclusive: bool = False
    cooldown_seconds: float = 0.0
    verification: MacroVerification | None = None
    reward_score: float = 0.0        # cumulative reward/punish
    uses: int = 0
    verified: bool = False
    published: bool = False
    source: str = "macro_agent"      # macro_agent | distillation | synthesizer | reflex


class MacroAgent:
    """AI macro generation + verification + reward/punish + registry."""

    def __init__(
        self,
        *,
        llm_generate: Callable[..., Any] | None = None,
        workspace_root: Path | None = None,
        verifier: MacroVerifier | None = None,
    ) -> None:
        self._llm = llm_generate
        self._verifier = verifier or MacroVerifier()
        if workspace_root is None:
            workspace_root = Path(__file__).resolve().parents[3]  # repo root
        self._root = workspace_root
        self._registry_dir = self._root / "macros"
        self._registry_dir.mkdir(parents=True, exist_ok=True)
        self._registry_manifest = self._registry_dir / "macro_manifest.json"
        self._generated: dict[str, GeneratedMacro] = {}
        self._load_registry()

    # ── Registry (shared, committed, reusable) ──────────────────────────
    def _load_registry(self) -> None:
        if not self._registry_manifest.exists():
            return
        try:
            data = json.loads(self._registry_manifest.read_text())
            for item in data.get("macros", []):
                gm = GeneratedMacro(
                    name=item["name"], lines=item["lines"], case=item.get("case", ""),
                    category=item.get("category", "custom"),
                    priority=int(item.get("priority", 50)),
                    triggers=item.get("triggers", []),
                    exclusive=bool(item.get("exclusive", False)),
                    cooldown_seconds=float(item.get("cooldown_seconds", 0.0)),
                    reward_score=float(item.get("reward_score", 0.0)),
                    uses=int(item.get("uses", 0)),
                    verified=bool(item.get("verified", False)),
                    published=bool(item.get("published", False)),
                    source=item.get("source", "macro_agent"),
                )
                self._generated[gm.name] = gm
        except Exception:
            logger.warning("macro_registry_load_failed", exc_info=True)

    def _save_registry(self) -> None:
        payload = {
            "macros": [
                {
                    "name": gm.name, "lines": gm.lines, "case": gm.case,
                    "category": gm.category, "priority": gm.priority,
                    "triggers": gm.triggers, "exclusive": gm.exclusive,
                    "cooldown_seconds": gm.cooldown_seconds,
                    "reward_score": gm.reward_score, "uses": gm.uses,
                    "verified": gm.verified, "published": gm.published,
                    "source": gm.source,
                }
                for gm in self._generated.values()
            ]
        }
        tmp = self._registry_manifest.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False))
        tmp.replace(self._registry_manifest)

    def registry(self) -> list[dict[str, Any]]:
        return [
            {
                "name": gm.name, "case": gm.case, "category": gm.category,
                "priority": gm.priority, "verified": gm.verified,
                "published": gm.published, "reward_score": gm.reward_score,
                "uses": gm.uses, "source": gm.source,
            }
            for gm in self._generated.values()
        ]

    # ── Generation (LLM) ─────────────────────────────────────────────────
    def generate(
        self,
        *,
        case: str,
        context: dict[str, Any] | None = None,
        bot_id: str = "default",
    ) -> GeneratedMacro | None:
        """Ask the LLM to generate a macro for a specific case.

        The prompt is agnostic (RULE.md): it instructs the LLM to use only
        @keyword() placeholders and DB-backed slots, never hardcoded item/map
        names. Server facts are injected via `context` (e.g. guild map, NPC
        coords, item names from the server_solutions store).
        """
        if self._llm is None:
            logger.warning("macro_agent_no_llm: cannot generate for case=%s", case)
            return None

        ctx = context or {}
        prompt = self._build_prompt(case, ctx)
        try:
            raw = self._llm(prompt, bot_id=bot_id, workload="macro_generation")
            # generate_text is async — await it if it returns a coroutine
            if hasattr(raw, "__await__"):
                import asyncio
                try:
                    raw = asyncio.get_event_loop().run_until_complete(raw)
                except RuntimeError:
                    # already inside a running loop — run on a fresh thread
                    import threading
                    result_holder: dict[str, Any] = {}
                    def _run():
                        result_holder["raw"] = asyncio.run(raw)
                    t = threading.Thread(target=_run, daemon=True)
                    t.start()
                    t.join()
                    raw = result_holder.get("raw")
        except Exception as exc:
            logger.warning("macro_agent_generate_failed case=%s err=%s", case, exc)
            return None
        if not raw or not raw.strip():
            logger.warning("macro_agent_empty_generation case=%s", case)
            return None

        macro = self._parse_llm_macro(raw, case, ctx)
        if macro is None:
            return None

        # Verify immediately (parse + security + dry-run + outcome)
        macro.verification = self._verifier.verify(
            self._render(macro), event_macro_text=""
        )
        macro.verified = macro.verification.ok
        if not macro.verified:
            logger.warning(
                "macro_agent_verify_failed case=%s name=%s errors=%s",
                case, macro.name, macro.verification.errors,
            )
        return macro

    def _build_prompt(self, case: str, ctx: dict[str, Any]) -> str:
        return (
            "You are the OpenKore macro engineer. Generate a single OpenKore "
            "`macro` block that handles this specific case.\n"
            f"CASE: {case}\n"
            f"CONTEXT: {json.dumps(ctx, ensure_ascii=False)}\n\n"
            "RULES (hard):\n"
            "1. Output ONLY a JSON object with a single key 'macro' whose value is "
            "the macro block text, e.g.:\n"
            '   {"macro": "macro my_case {\\n    log handling case\\n    '
            'move <map> <x> <y>\\n    talknpc <x> <y> c\\n    stop\\n}"}\n'
            "2. Use ONLY these commands: do, log, pause, stop, release, lock, "
            "call, goto, move, talk, talknpc, use, store, buy, sell, attack, "
            "sit, stand, teleport, ai, conf, set, equip, unequip, party, follow, "
            "send, c, reply, deal, drop, get, put, open, close, respawn, skill.\n"
            "3. NEVER hardcode item/map/server names. Use the CONTEXT values "
            "(map, x, y, npc, item) verbatim — they are DB-backed server facts.\n"
            "4. NEVER use eval, shell, system, exec, wget, curl, perl, @eval, "
            "or 'move 0 0'.\n"
            "5. End with 'stop'.\n"
            "6. The macro name must be lowercase, alphanumeric + _ . : -\n"
            "7. If the case needs a menu selection, use 'talknpc <x> <y> c r<N>' "
            "where N is the menu option index.\n"
            "8. Escape newlines and quotes properly inside the JSON string.\n"
        )

    def _parse_llm_macro(self, raw: str, case: str, ctx: dict[str, Any]) -> GeneratedMacro | None:
        # The LLM may return a JSON object {"macro": "..."} (adapter forces JSON)
        # OR a bare macro block. Handle both.
        macro_text = raw
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict) and isinstance(parsed.get("macro"), str):
                macro_text = parsed["macro"]
        except Exception:
            pass
        # Extract the macro block
        m = re.search(r"macro\s+([A-Za-z0-9_.:-]+)\s*\{(.*?)\}", macro_text, re.S)
        if not m:
            logger.warning("macro_agent_no_block_in_llm_output case=%s", case)
            return None
        name = m.group(1).strip()
        body = m.group(2)
        lines = [ln.strip() for ln in body.splitlines() if ln.strip()]
        if not lines:
            return None
        return GeneratedMacro(
            name=name, lines=lines, case=case,
            category=ctx.get("category", "custom"),
            priority=int(ctx.get("priority", 50)),
            triggers=ctx.get("triggers", []),
            exclusive=bool(ctx.get("exclusive", False)),
            cooldown_seconds=float(ctx.get("cooldown_seconds", 0.0)),
        )

    def _render(self, macro: GeneratedMacro) -> str:
        lines = ["# Generated by openkore-ai-sidecar macro-agent; do not edit manually.", ""]
        lines.append(f"macro {macro.name} {{")
        for ln in macro.lines:
            lines.append(f"    {ln}")
        lines.append("}")
        return "\n".join(lines) + "\n"

    # ── Register (add to MacroIntelligence as a skill-set pattern) ───────
    def register(self, macro: GeneratedMacro, macro_intelligence: Any | None = None) -> bool:
        """Register a verified macro as a MacroPattern (skill-set) in the engine."""
        if not macro.verified:
            logger.warning("macro_agent_register_unverified name=%s", macro.name)
            return False
        if macro_intelligence is not None and hasattr(macro_intelligence, "add_custom_pattern"):
            from ai_sidecar.autonomy.macro_intelligence import (
                MacroAction, MacroPattern, MacroTrigger,
            )
            pattern = MacroPattern(
                pattern_id=macro.name,
                category=macro.category,
                description=f"AI macro-agent: {macro.case}",
                triggers=[MacroTrigger(**t) for t in macro.triggers],
                action_sequence=[MacroAction(command=ln) for ln in macro.lines],
                priority=macro.priority,
                exclusive=macro.exclusive,
                cooldown_seconds=macro.cooldown_seconds,
            )
            macro_intelligence.add_custom_pattern(pattern)
        self._generated[macro.name] = macro
        self._save_registry()
        return True

    # ── Reward / punish (self-improving) ─────────────────────────────────
    def reward(self, macro_name: str, *, bot_id: str, event: str = MACRO_REWARD,
               detail: str = "") -> None:
        """Credit a macro for a successful outcome (self-improving)."""
        gm = self._generated.get(macro_name)
        if gm is None:
            return
        gm.reward_score += 0.5
        gm.uses += 1
        self._save_registry()
        try:
            from ai_sidecar.learning.brain_reward_ledger import get_brain_reward_ledger
            get_brain_reward_ledger().record(bot_id, "macro", event, detail)
        except Exception:
            logger.debug("macro_reward_ledger_failed", exc_info=True)

    def punish(self, macro_name: str, *, bot_id: str, event: str = MACRO_PUNISH,
               detail: str = "") -> None:
        """Punish a macro for a failed outcome (self-improving)."""
        gm = self._generated.get(macro_name)
        if gm is None:
            return
        gm.reward_score -= 0.5
        gm.uses += 1
        self._save_registry()
        try:
            from ai_sidecar.learning.brain_reward_ledger import get_brain_reward_ledger
            get_brain_reward_ledger().record(bot_id, "macro", event, detail)
        except Exception:
            logger.debug("macro_punish_ledger_failed", exc_info=True)

    def promote(self, macro_name: str) -> bool:
        """Promote a macro to the shared registry (committed, reusable)."""
        gm = self._generated.get(macro_name)
        if gm is None or not gm.verified:
            return False
        gm.published = True
        self._save_registry()
        return True

    def demote(self, macro_name: str) -> bool:
        """Demote/remove a macro that repeatedly failed."""
        gm = self._generated.get(macro_name)
        if gm is None:
            return False
        if gm.reward_score < -2.0:
            del self._generated[macro_name]
            self._save_registry()
            return True
        return False
