from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from ai_sidecar.contracts.macros import EventAutomacro, MacroRoutine

_NAME_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")


@dataclass(slots=True)
class CompiledMacroArtifacts:
    publication_id: str
    version: str
    content_sha256: str
    published_at: datetime
    macro_text: str
    event_macro_text: str
    manifest: dict[str, object]


class MacroCompiler:
    def compile(
        self,
        *,
        macros: list[MacroRoutine],
        event_macros: list[MacroRoutine],
        automacros: list[EventAutomacro],
    ) -> CompiledMacroArtifacts:
        normalized_macros = self._normalize_routines(macros)
        normalized_event_macros = self._normalize_routines(event_macros)
        normalized_automacros = self._normalize_automacros(automacros)

        event_macro_block = self._render_event_file(normalized_event_macros, normalized_automacros)
        macro_block = self._render_macro_file(normalized_macros)

        manifest_payload = {
            "macro_names": [routine.name for routine in normalized_macros],
            "event_macro_names": [routine.name for routine in normalized_event_macros],
            "automacro_names": [item.name for item in normalized_automacros],
            "macro_text": macro_block,
            "event_macro_text": event_macro_block,
        }
        canonical = json.dumps(manifest_payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        published_at = datetime.now(UTC)
        version = f"v{published_at.strftime('%Y%m%d%H%M%S')}-{digest[:12]}"
        publication_id = digest[:24]

        manifest: dict[str, object] = {
            "publication_id": publication_id,
            "version": version,
            "published_at": published_at.isoformat(),
            "content_sha256": digest,
            "macro_file": "control/ai_sidecar_generated_macros.txt",
            "event_macro_file": "control/ai_sidecar_generated_eventmacros.txt",
            "macro_count": len(normalized_macros),
            "event_macro_count": len(normalized_event_macros),
            "automacro_count": len(normalized_automacros),
            "macro_names": [routine.name for routine in normalized_macros],
            "event_macro_names": [routine.name for routine in normalized_event_macros],
            "automacro_names": [item.name for item in normalized_automacros],
        }

        return CompiledMacroArtifacts(
            publication_id=publication_id,
            version=version,
            content_sha256=digest,
            published_at=published_at,
            macro_text=macro_block,
            event_macro_text=event_macro_block,
            manifest=manifest,
        )

    def _normalize_routines(self, routines: list[MacroRoutine]) -> list[MacroRoutine]:
        by_name: dict[str, MacroRoutine] = {}
        for routine in routines:
            self._validate_name(routine.name)
            clean_lines = [self._sanitize_line(line) for line in routine.lines]
            by_name[routine.name] = MacroRoutine(name=routine.name, lines=clean_lines)
        return [by_name[name] for name in sorted(by_name)]

    def _normalize_automacros(self, automacros: list[EventAutomacro]) -> list[EventAutomacro]:
        by_name: dict[str, EventAutomacro] = {}
        for item in automacros:
            self._validate_name(item.name)
            self._validate_name(item.call)

            normalized_conditions = [self._sanitize_line(line) for line in item.conditions if self._sanitize_line(line)]
            if not normalized_conditions:
                normalized_conditions = ["BaseLevel >= 1"]

            normalized_parameters: dict[str, str] = {}
            for key in sorted(item.parameters):
                clean_key = self._sanitize_line(key)
                clean_val = self._sanitize_line(item.parameters[key])
                if not clean_key:
                    continue
                normalized_parameters[clean_key] = clean_val

            by_name[item.name] = EventAutomacro(
                name=item.name,
                conditions=normalized_conditions,
                call=item.call,
                parameters=normalized_parameters,
            )
        return [by_name[name] for name in sorted(by_name)]

    def _render_macro_file(self, routines: list[MacroRoutine]) -> str:
        lines: list[str] = [
            "# Generated by openkore-ai-sidecar; do not edit manually.",
            "",
        ]
        for routine in routines:
            lines.append(f"macro {routine.name} {{")
            for line in routine.lines:
                lines.append(f"    {line}")
            lines.append("}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _render_event_file(self, event_macros: list[MacroRoutine], automacros: list[EventAutomacro]) -> str:
        lines: list[str] = [
            "# Generated by openkore-ai-sidecar; do not edit manually.",
            "",
        ]

        for item in automacros:
            lines.append(f"automacro {item.name} {{")
            for condition in item.conditions:
                lines.append(f"    {condition}")
            for key in sorted(item.parameters):
                lines.append(f"    {key} {item.parameters[key]}")
            lines.append(f"    call {item.call}")
            lines.append("}")
            lines.append("")

        for routine in event_macros:
            lines.append(f"macro {routine.name} {{")
            for line in routine.lines:
                lines.append(f"    {line}")
            lines.append("}")
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _validate_name(self, name: str) -> None:
        if not _NAME_RE.fullmatch(name):
            raise ValueError(f"invalid macro name '{name}'")

    def _sanitize_line(self, line: str) -> str:
        clean = line.replace("\r", " ").replace("\n", " ").strip()
        return clean


class MacroPublisher:
    def __init__(self, workspace_root: Path) -> None:
        self._workspace_root = workspace_root
        self._control_dir = workspace_root / "control"

    @property
    def macro_file(self) -> Path:
        return self._control_dir / "ai_sidecar_generated_macros.txt"

    @property
    def event_macro_file(self) -> Path:
        return self._control_dir / "ai_sidecar_generated_eventmacros.txt"

    @property
    def catalog_file(self) -> Path:
        return self._control_dir / "ai_sidecar_macros.txt"

    @property
    def manifest_file(self) -> Path:
        return self._control_dir / "ai_sidecar_macro_manifest.json"

    def relpath(self, path: Path) -> str:
        return str(path.relative_to(self._workspace_root))

    def publish(self, compiled: CompiledMacroArtifacts) -> None:
        self._control_dir.mkdir(parents=True, exist_ok=True)

        backups = {
            self.macro_file: self.macro_file.read_text(encoding="utf-8") if self.macro_file.exists() else None,
            self.event_macro_file: self.event_macro_file.read_text(encoding="utf-8") if self.event_macro_file.exists() else None,
            self.catalog_file: self.catalog_file.read_text(encoding="utf-8") if self.catalog_file.exists() else None,
            self.manifest_file: self.manifest_file.read_text(encoding="utf-8") if self.manifest_file.exists() else None,
        }

        try:
            self._atomic_write(self.macro_file, compiled.macro_text)
            self._atomic_write(self.event_macro_file, compiled.event_macro_text)
            self._atomic_write(self.catalog_file, self._render_catalog(compiled))
            self._atomic_write(self.manifest_file, json.dumps(compiled.manifest, ensure_ascii=False, indent=2) + "\n")
        except Exception:
            for path, content in backups.items():
                if content is None:
                    if path.exists():
                        path.unlink()
                else:
                    self._atomic_write(path, content)
            raise

    def _render_catalog(self, compiled: CompiledMacroArtifacts) -> str:
        lines = [
            "######## AI Sidecar Macro Catalog ########",
            "# Generated by AI sidecar runtime publisher.",
            f"aiSidecarMacro_publicationId {compiled.publication_id}",
            f"aiSidecarMacro_version {compiled.version}",
            f"aiSidecarMacro_publishedAt {compiled.published_at.isoformat()}",
            f"aiSidecarMacro_contentSha256 {compiled.content_sha256}",
            "aiSidecarMacro_macroFile control/ai_sidecar_generated_macros.txt",
            "aiSidecarMacro_eventMacroFile control/ai_sidecar_generated_eventmacros.txt",
        ]
        return "\n".join(lines) + "\n"

    def _atomic_write(self, path: Path, content: str) -> None:
        tmp_path = path.with_suffix(path.suffix + ".tmp")
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(path)
